// THIS FILE WAS GENERATED BY `xtp-cpp-bindgen`. DO NOT EDIT.
#include <chrono>
#include <cstddef>
#include <expected>
#include <memory>
#include <span>
#include <stdint.h>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace pdk {

// Input params for clear() import
struct InputClear {
  //
  int32_t color;
};

// Input params for update() export
struct InputUpdate {
  //
  double time;
};

// host function errors
enum class Error { extism, host_null, not_json, json_null, not_implemented };

/**
 * Clear the screen with a color
 *
 * @param input
 */
std::expected<void, Error> clear(InputClear input);

} // namespace pdk

namespace impl {

/**
 * Called when your cart is loaded
 */
std::expected<void, pdk::Error> load();

/**
 * Called when your cart is unloaded
 */
std::expected<void, pdk::Error> unload();

/**
 * Called each frame
 *
 * @param input
 */
std::expected<void, pdk::Error> update(pdk::InputUpdate input);

} // namespace impl
